repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.5.0
    hooks:
    -   id: seed-isort-config
        language_version: python3.6

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
        language_version: python3.6

